version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgres_users
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: U2024u@24
      POSTGRES_DB: users_db
    ports:
      - "5434:5432"
    volumes:
      - users_data:/var/lib/postgresql/data

volumes:
  users_data:
